language: php

env:
  matrix:
    - NETTE=nette-2.3

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update

install:
  - export PATH="$PATH:$HOME/.composer/vendor/bin"
  - composer global require fabpot/php-cs-fixer dev-master
  - composer update --no-interaction --prefer-source

before_script:
  - vendor/bin/codecept build

script:
  - php-cs-fixer fix --dry-run
  - vendor/bin/codecept run
